name: tests

on:
    push:
        branches: [ main ]
    pull_request:

permissions:
    contents: write

jobs:
    tests:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [ 8.2, 8.3 ]

        name: PHP ${{ matrix.php }}

        steps:
            - name: Checkout the code
              uses: actions/checkout@v4

            - name: Get composer cache directory path
              id: composercache
              run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            - name: Cache composer
              uses: actions/cache@v3
              with:
                path: ${{ steps.composercache.outputs.dir }}
                key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  tools: composer:v2
                  coverage: none

            - name: Install dependencies
              run: composer update --prefer-dist --no-interaction --no-progress

            - name: Execute the tests
              run: ./vendor/bin/pest --compact
